FROM hashicorp/packer:1.4.3

LABEL "com.github.actions.name"="Packer"
LABEL "com.github.actions.description"="Build images with packer"
LABEL "com.github.actions.icon"="mic"
LABEL "com.github.actions.color"="purple"

LABEL "repository"="http://github.com/jrbeverly/packer-on-github"
LABEL "homepage"="http://github.com/actions"
LABEL "maintainer"="jrbeverly <jonathan@jrbeverly.me>"

RUN apk add --no-cache jq curl
